Algoritmo "semnome"
// Fazer a multiplicação, soma, divisão e subtração de dois número.
Var
num1, num2: inteiro


Inicio
 escreva("Digite um número inteiro: ")
 leia(num1)
 escreva("Digite o segundo número inteiro: ")
 leia(num2)
 escreval("A soma dos dois números são: ", num1+num2)
 escreval("A subtração dos dois números são: ", num1-num2)
 escreval("A divisão entre os dois números são: ", num1/num2)
 escreval("A multiplicação entre os dois números são: ", num1*num2)


Fimalgoritmo