Algoritmo "semnome"
// Construa um algoritmo que receba dois números
//e mostre quando o primeiro for maior e quando for menor que o segundo.
Var
numero1, numero2, maior, menor: inteiro


Inicio
 escreva("Digite o primeiro número: ")
 leia(numero1)
 escreva("Digite o segundo número: ")
 leia(numero2)
 se (numero1>numero2) entao
  escreva(numero1, " é maior que", numero2)
  senao
  escreva(numero1, " é menor que", numero2)
fimse

Fimalgoritmo