Algoritmo "semnome"
// um algoritmo que receba um número e mostre a sua metade somente quando
//for maior
Var
 numero, metade: inteiro


Inicio
  escreva("Digite um número: ")
  leia (numero)
  metade <-numero \ 2 // divisão para inteiro vai ser div ou barra invertida
  se (metade >= 50) entao
  escreva("A sua metade é: ", metade)
  fimse
  escreval("Esse número não é maior na sua metade")
  



Fimalgoritmo