Algoritmo "semnome"
// Faça o algoritmo para ler um número qualquer e verificar se este número
//  é maior ou igual a 10. Para a opção verdadeira mostrar a palavra
//“Maior”, senão mostrar “Menor”.
Var
numero, maior, menor: inteiro


Inicio

  escreval("Digite um número: ")
  leia (numero)
  se (numero>=10) entao
  escreva("O número", numero, " é maior ou igual à 10")
  
  senao
  escreval("O número", numero, " é menor que 10")
  fimse


Fimalgoritmo